### GET request to validate Token
GET http://localhost:4005/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MTg1MzUzMCwiZXhwIjoxNzcxODg5NTMwfQ.qyNdzI2jlCD7jW1zg79JFijpywd6UzOAWG_ku1mZC_Y